const API = 'http://localhost:8000/api/v1';
const $ = (id) => document.getElementById(id);
const request = async (path, options) => { const response = await fetch(API + path, options); const body = await response.json(); if (!response.ok) throw new Error(body.error || `Request failed: ${response.status}`); return body.data; };
const setText = (id, value) => { if ($(id)) $(id).textContent = value; };
const showMessage = (text) => { $('message').textContent = text; $('message').classList.remove('hidden'); };
const assetUrl = (path) => path ? `http://localhost:8000${path}` : '';
let map = L.map('map').setView([27.4728, 94.912], 10);
L.tileLayer('https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}', { attribution: 'Tiles &copy; Esri' }).addTo(map);
let markers = [];
function renderMap(lat, lon, settlements) { markers.forEach((marker) => marker.remove()); markers = []; const hasCoordinates = lat !== null && lat !== undefined && lon !== null && lon !== undefined; const center = hasCoordinates ? [Number(lat), Number(lon)] : [27.4728, 94.912]; map.setView(center, hasCoordinates ? 12 : 10); if (hasCoordinates) markers.push(L.marker(center).addTo(map).bindPopup('Drone survey location')); (settlements || []).forEach((item) => markers.push(L.marker([item.latitude, item.longitude]).addTo(map).bindPopup(`${item.name} · ${item.severity}`))); setText('coordinates', hasCoordinates ? `Survey location: ${Number(lat).toFixed(5)}, ${Number(lon).toFixed(5)}` : 'Survey location pending'); }
function renderRows(id, rows, empty, valueLabel = 'Status') { const node = $(id); node.innerHTML = rows.length ? rows.slice(0, 5).map((row) => `<div><b>${row.name || row.asset}</b><span>${row.status || row.type || valueLabel}</span></div>`).join('') : `<span>${empty}</span>`; }
function renderSettlements(items) { const node = $('settlement-list'); node.innerHTML = items.length ? `<table><thead><tr><th>Settlement</th><th>Impact level</th><th>Population</th></tr></thead><tbody>${items.slice(0, 6).map((item) => `<tr><td><b>${item.name}</b></td><td><span class="badge ${String(item.severity).toLowerCase().includes('critical') || String(item.severity).toLowerCase().includes('severe') ? 'severe' : String(item.severity).toLowerCase().includes('moderate') ? 'moderate' : 'low'}">${item.severity}</span></td><td>${item.population}</td></tr>`).join('')}</tbody></table>` : '<div class="empty"><b>No settlements identified yet</b><span>Survey observations will appear here.</span></div>'; }
function renderEvidence(latest) { const node = $('survey-output'); if (!latest.imagePath) { node.innerHTML = '<div class="empty"><b>Awaiting Drone Survey</b><span>Upload imagery to populate evidence.</span></div>'; return; } const original = latest.mediaType === 'VIDEO' ? `<video src="${assetUrl(latest.imagePath)}" controls preload="metadata" aria-label="Original drone survey video"></video>` : `<img src="${assetUrl(latest.imagePath)}" alt="Flooded area survey">`; node.innerHTML = `<figure>${original}<figcaption>${latest.mediaType === 'VIDEO' ? 'Survey Video' : 'Flooded Area'}</figcaption></figure><figure><img src="${assetUrl(latest.annotatedImagePath)}" alt="Annotated drone survey"><figcaption>Survey Analysis</figcaption></figure><figure class="evidence-empty"><span>Road Blockage</span></figure><figure class="evidence-empty"><span>Damaged Bridge</span></figure>`; }
async function loadDashboard() { try { const latest = await request('/analysis/latest'); const [flood, settlements, roads, infrastructure] = await Promise.all(['/assessment/flood','/assessment/settlements','/assessment/roads','/assessment/infrastructure'].map((path) => request(path))); const people = (latest.detections || []).filter((item) => /person|people/i.test(item.class)).length; setText('coverage', `${Number(flood.floodAreaSqKm || 0).toFixed(1)} km²`); setText('people-count', people); setText('settlements-count', settlements.observedCount); setText('open-roads', settlements.observedCount); setText('assets-count', roads.blockedRoads + roads.submergedRoads); setText('priority', infrastructure.atRisk + infrastructure.flooded); setText('flood-coverage', `${flood.coveragePercentage.toFixed(1)}%`); setText('spread', flood.direction); setText('trend', flood.trend); setText('assessment-status', 'Reviewed'); setText('survey-time', new Date(latest.recordedAt).toLocaleString()); setText('road-open', roads.openRoads); setText('road-partial', roads.blockedRoads); setText('road-blocked', roads.submergedRoads); setText('infra-safe', infrastructure.accessible); setText('infra-risk', infrastructure.atRisk); setText('infra-affected', infrastructure.flooded); $('report-top').disabled = false; $('report-main').disabled = false; renderMap(latest.latitude, latest.longitude, settlements.settlements); renderRows('road-list', roads.roads || [], 'No road observations yet.'); renderRows('infra-list', infrastructure.assets || [], 'No infrastructure observations yet.'); renderSettlements(settlements.settlements || []); renderEvidence(latest); setText('detections', `${people} people detected`); } catch (error) { showMessage(error.message); } }
async function downloadReport() { try { const response = await fetch(`${API}/report/download`); if (!response.ok) throw new Error('Report is not available yet.'); const blob = await response.blob(); const link = document.createElement('a'); link.href = URL.createObjectURL(blob); link.download = 'sky-guardian-assessment.pdf'; link.click(); URL.revokeObjectURL(link.href); } catch (error) { showMessage(error.message); } }
$('upload-mode').addEventListener('click', () => { $('upload-mode').classList.add('selected'); $('live-mode').classList.remove('selected'); $('upload-form').classList.remove('hidden'); $('live-state').classList.add('hidden'); });
$('live-mode').addEventListener('click', () => { $('live-mode').classList.add('selected'); $('upload-mode').classList.remove('selected'); $('upload-form').classList.add('hidden'); $('live-state').classList.remove('hidden'); });
$('upload-form').addEventListener('submit', async (event) => { event.preventDefault(); const file = $('media').files[0]; if (!file) return; const button = event.submitter; button.disabled = true; $('progress').classList.remove('hidden'); try { const form = new FormData(); form.append('image', file); const result = await request('/analysis/upload', { method: 'POST', body: form }); showMessage(result.latitude !== null && result.longitude !== null ? 'Survey assessed. GPS coordinates were extracted from the media metadata.' : 'Survey assessed. No embedded GPS metadata was found.'); $('upload-form').reset(); await loadDashboard(); } catch (error) { showMessage(error.message); } finally { button.disabled = false; $('progress').classList.add('hidden'); } });
$('media').addEventListener('change', () => { const file = $('media').files[0]; const preview = $('upload-preview'); if (!file) { preview.innerHTML = ''; preview.classList.add('hidden'); return; } const url = URL.createObjectURL(file); preview.classList.remove('hidden'); preview.innerHTML = file.type.startsWith('video/') ? `<video src="${url}" controls muted></video><span>${file.name}</span>` : `<img src="${url}" alt="Selected survey preview"><span>${file.name}</span>`; });
function saveBlob(content, filename, type) { const link = document.createElement('a'); link.href = URL.createObjectURL(new Blob([content], { type })); link.download = filename; link.click(); URL.revokeObjectURL(link.href); }
async function exportStructured(format) { try { const [settlements, roads, infrastructure] = await Promise.all(['/assessment/settlements','/assessment/roads','/assessment/infrastructure'].map((path) => request(path))); if (format === 'excel') { const rows = [['Category','Name','Status / Impact','Population / Type'], ...(settlements.settlements || []).map((item) => ['Settlement', item.name, item.severity, item.population]), ...(roads.roads || []).map((item) => ['Road', item.name, item.status, item.alternativeRoute || '']), ...(infrastructure.assets || []).map((item) => ['Infrastructure', item.asset, item.status, item.type])]; saveBlob(rows.map((row) => row.map((value) => `"${String(value).replace(/"/g, '""')}"`).join(',')).join('\n'), 'sky-guardian-assessment.csv', 'text/csv'); } else { const features = (settlements.settlements || []).map((item) => ({ type: 'Feature', properties: { name: item.name, severity: item.severity, population: item.population }, geometry: { type: 'Point', coordinates: [item.longitude, item.latitude] } })); saveBlob(JSON.stringify({ type: 'FeatureCollection', features }, null, 2), 'sky-guardian-settlements.geojson', 'application/geo+json'); } } catch (error) { showMessage(error instanceof Error ? error.message : 'Export failed.'); } }
$('report-excel').addEventListener('click', () => exportStructured('excel')); $('report-geojson').addEventListener('click', () => exportStructured('geojson')); $('report-top').addEventListener('click', downloadReport); $('report-main').addEventListener('click', downloadReport); $('report-action').addEventListener('click', downloadReport); loadDashboard().then(() => { ['report-action','report-excel','report-geojson','report-main','report-top'].forEach((id) => { if ($(id)) $(id).disabled = false; }); });
